Hide scrollbar on Firefox
BigWhaleLabs/seal-cred-frontend pull request #206
Opened 2022-05-24 20:25 UTC by T-Damer

2022-05-24 20:26 UTC, T-Damer commented on src/index.css
>    overflow: auto;
Overflow is necessary for self-written custom scrollbar

2022-05-24 22:46 UTC, backmeupplz requested changes

2022-05-24 22:46 UTC, backmeupplz commented on src/components/Scrollbar.tsx
> +    <div className="relative scrollbar-hide">
Use `tailwind-classnames`, at least for `relative`

2022-05-25 14:47 UTC, T-Damer commented on src/components/Scrollbar.tsx
> +        className={overflow('overflow-auto') + ' scrollbar-hide'}
I'd rather use `class` + `className`, but `className` overrides `class`

2022-05-25 16:07 UTC, merged