Make smooth tooltip
BigWhaleLabs/seal-cred-frontend pull request #219
Opened 2022-06-14 17:41 UTC by smyzin

- removed `react-tooltip` lib
- styled owned tooltip
- created `click outside` hook

2022-06-14 19:04 UTC, MixailE commented on src/components/ZkProofButton.tsx
> +      <div
Can we put the logic in `ToolTip`?

2022-06-14 19:46 UTC, smyzin commented on src/components/ZkProofButton.tsx
> +      <div
Did it. Thx

2022-06-15 04:31 UTC, T-Damer commented on src/components/ToolTip.tsx
> +    margin('!ml-0'),
Do we need important here if we don't override original library?

2022-06-15 04:31 UTC, T-Damer commented on src/components/ToolTip.tsx
> +    borderRadius('!rounded-lg'),
Do we need important here if we don't override original library?

2022-06-15 04:33 UTC, T-Damer commented on src/components/ToolTip.tsx
> +    inset('bottom-4'),
Let's move this inset(content) inside another

2022-06-15 04:34 UTC, T-Damer commented on src/components/ToolTip.tsx
> +        className={width('w-full')}
Let's extract this into `variable` so we can change it fast if needed

2022-06-15 04:35 UTC, T-Damer commented on src/hooks/useClickOutside.ts
> +      if (ref.current && !ref.current.contains(event.target as Node)) {
You can go without `{}` here

2022-06-15 04:35 UTC, T-Damer commented on src/hooks/useClickOutside.ts
> +    return () => {
And here

2022-06-15 04:36 UTC, T-Damer requested changes
Need a little code cleaning, otherwise looks pretty good

2022-06-15 12:29 UTC, T-Damer approved these changes
lgtm, great work :)

2022-06-15 12:30 UTC, merged