Relay provider back to scene with crypto
BigWhaleLabs/seal-cred-frontend pull request #414
Opened 2022-08-09 07:35 UTC by T-Damer

2022-08-09 12:21 UTC, upacyxou commented
otherwise lgtm

2022-08-09 12:22 UTC, upacyxou requested changes

2022-08-09 12:22 UTC, upacyxou commented on src/helpers/providers/relayProvider.ts
> -const GasPricePingFilter: PingFilter = (
I don't think that we need to remove this, all of my local test was successful with this filter

2022-08-09 12:23 UTC, upacyxou approved these changes

2022-08-09 15:02 UTC, backmeupplz requested changes

2022-08-09 15:02 UTC, backmeupplz commented on vite.config.ts
> +  resolve: { alias: { assert: 'assert-browserify' } },
We should check if removing `assert` from `inject` below breaks proof generation or minting

2022-08-11 16:32 UTC, backmeupplz approved these changes

2022-08-11 16:32 UTC, merged